### ISSUE TITLE
Question : about queue_.put() and asyncio.create_task()

### ISSUE THREAD

**Issue by wwdok** [ShahriyarR/concurrent-camera-reader#16]
Hi, @ShahriyarR Thanking for sharing this useful project that has great reference value for separating the display and model inference. After reading the source code, i have a few questions :
1. In `main.py`, there are three `queue_.put()` : 
```
1. queue_.put(await task1)
2. await queue_.put(frame)
3. await queue_.put((camera_name, frame))
```
each queue_.put() put different items, and you use `frame = await queue_.get()` two times to get only the frame, so if you don't get task1, camera_name, why did you put them in the queue ? and how do you ensure that the return of  `queue_.get()` is only the frame ?

2. for this line of code : `frame = await asyncio.create_task(captured_obj.read_frame(cap), name="frame_reader")`. The return of `create_task` is a Task object, isn't it ? and you assign it to `frame`, this `frame` is a task object or a BGR numpy array type frame ?

I will very appreciate it if you could give me some tips ? Thanks !

**Comment by wwdok** [comment]
about the second question, i printed out `frame`, it turns out it is really BGR numpy array, maybe adding `await` before task object will rerurn the result of `read_frame(cap)`.

**Comment by ShahriyarR** [comment]
Hi @wwdok,
I am also recording all steps for building this project on [Youtube](https://www.youtube.com/playlist?list=PL0xSLrZOcI4t-ABy2BGc12YT1Hmm8f9iD), I am going to record the last changes this weekend. So you should expect frequent code and flow changes here :)
Please git pull in the `main` branch, to get recent changes. Let me explain what I am trying to achieve here:
* In the `produce()` function I read the frames from cameras and put those frame into the queue:
`await queue_.put([camera_name, frame, None])` -> the None indicates here that this frames is not processed yet and it is a fresh one. So basically in this function, I  am producing the frames.

* There is a `consume()` function which should do:
      - get the frame from the queue.
      - pass this frame to `run_fd_time()` function which is going to add a timestamp to the frame and put it back to the queue (updated frame) -> `await queue_.put(await task1)` 
      - after putting the timestamped frame into the queue, the queue was passed to `show_frame()` which is going to get the frame from the queue and show it.
      - there is also `run_blocking_func()` function which is running the inference in the external executor - effectively the blocking code. The logic is simple here also, it gets the frame from the queue, apply face detection, put it back to the queue -> `await queue_.put(frame)`. Here the `frame` is a list object with 3 members but now it is `[camera_name, frame, True]` -> True indicates that this frame was processed.
     > As you see from recent changes I have temporarily disabled `run_blocking_func()` call on the consumer side as it is not working correctly. After fixing this issue I will record the video explanation as well.

About your second question:
`asyncio.create_task()` is creating a Task object. `await asyncio.create_task()` -> will execute it. So the `read_frame()` itself is an awaitable, I wrap it into the Task and then await this task.

Please do not hesitate to ask extra questions, I am quite happy to help.

**Comment by wwdok** [comment]
What a detailed explanations ! I have subsribed to your youtube channel, i am expecting your new up-coming videos !
For the 1st question, i have figure it out by knowing these points:
`queue_.put(await task1)` is just like second question, they all return the `frame` list. The `frame` actually is a list that equals `[camera_name, frame, True]`, why not use different names to distinguish these two `frame`, I was trapped by this at first, hahaha.
For the 2nd question, it is easy to understand now, it is just a sub-question of 1st question.
You says `run_blocking_func()` did not working correctly, i have not found this issue, i just test the demo on my desktop, the code   can display successfully the frames grabbed by opencv.

**Comment by ShahriyarR** [comment]
:) Thanks for subscribing. Yeap I am going to record 3 or 4 videos about using asyncio.queue as we have discussed here but with further explanations.
Hmm, I think I should definitely make an extra effort in documenting the code or changing some variable names, I totally agree with you it is a bit confusing at a first look.
Yes, you got it - the frame itself is a list of `[camera_name, frame, None/True]`.
The final idea of this project - to manage frames in an async manner that, will lag as minimal as possible - so `run_blocking_func()` will add `ROI`s to the frame and put it back to the queue after that an extra consumer can grab the processed frames and show them - we will see how it is going to happen, so stay tuned.
